# Generated by Django 3.0.4 on 2020-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0002_auto_20200311_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='role',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
