# Generated by Django 3.0.4 on 2020-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0003_user_details_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=1)),
                ('city', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
